database_separator/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import DataBaseDetailView, SeparationView, CheckView, AdditionalFunctionalityView, CheckSumsView, \
    initialize, replication_relaunch, checksums


app_name = 'database_separator'

urlpatterns = [
    path('database/<int:pk>', login_required(DataBaseDetailView.as_view()), name='db'),
    path('checksums', login_required(CheckSumsView.as_view()), name='checksums'),
    path('separate', login_required(SeparationView.as_view()), name='separate'),
    path('check/', login_required(CheckView.as_view()), name='check'),
    path('additional', login_required(AdditionalFunctionalityView.as_view()), name='additional'),
    path('initialize', login_required(initialize), name='initialize'),
    path('relaunch', login_required(replication_relaunch), name='relaunch'),
    path('save_checksums', login_required(checksums), name='save_checksums')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views import generic
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required

from database_separator.views import MyLoginView, IndexTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('database_separator/', include('database_separator.urls', namespace='database_separator')),
    path('accounts/login/', MyLoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('', login_required(IndexTemplateView.as_view(template_name='index.html')), name='index')
]

urlpatterns += staticfiles_urlpatterns()

database_separator/models.py
from django.db import models
from django.db.utils import ProgrammingError


class DataBase(models.Model):
    name = models.CharField('Название БД', max_length=250,)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'База данных'
        verbose_name_plural = 'Базы данных'


class Publication(models.Model):
    database = models.ForeignKey(DataBase, on_delete=models.CASCADE, verbose_name='БД', related_name='publications')
    name = models.CharField('Название публикации', max_length=250)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'


class PubTables(models.Model):
    pub = models.ForeignKey(Publication, on_delete=models.CASCADE, verbose_name='Публикация', related_name='tables')
    name = models.CharField('Таблица в публикации', max_length=250, blank=True)

    def __str__(self):
        return self.name


class Subscription(models.Model):
    database = models.ForeignKey(DataBase, on_delete=models.CASCADE, verbose_name='БД', related_name='subscriptions')
    name = models.CharField('Название подписки', max_length=250)
    to_database = models.ForeignKey(DataBase, on_delete=models.CASCADE, verbose_name='к БД', related_name='sub_to_me',
                                    null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'


class ReplicationSlot(models.Model):
    database = models.ForeignKey(DataBase, on_delete=models.CASCADE, verbose_name='БД',
                                 related_name='replication_slots')
    name = models.CharField('Название слота', max_length=250)
    active = models.BooleanField('Активен', null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Слот репликации'
        verbose_name_plural = 'Слоты репликации'


class SequenceRange(models.Model):
    start = models.IntegerField('Начальное значение')
    max = models.IntegerField('Конечное значение')
    database = models.CharField('БД', max_length=250, null=True, blank=True)
    number = models.PositiveIntegerField('Порядковый номер', blank=True, null=True)

    def __str__(self):
        return f'Диапазон для {self.database}'

    @classmethod
    def get_next_range(cls):
        try:
            last_range = cls.objects.order_by('number').last()
            start = last_range.start/10**16
            max = last_range.max/10**16
            return {'start': (start + 2)*10**16, 'max': (max + 2)*10**16 - 1}
        except:
            return {'start': '', 'max': ''}

    class Meta:
        verbose_name = 'Диапазон для БД'
        verbose_name_plural = 'Диапазоны для БД'


class CheckSum(models.Model):
    checksum = models.IntegerField('Контрольная сумма')
    date = models.DateTimeField('Время добавления', auto_now_add=True)

    class Meta:
        verbose_name = 'Контрольная сумма'
        verbose_name_plural = 'Контрольные суммы'

database_separator/forms.py
from psycopg2 import connect as pgconnect

from django import forms

from .scripts.separation import connect
from .models import DataBase


class SeparationForm(forms.Form):
    """
    Форма для раздления
    Поля:
        app_name - название приложения
        db_name - название БД
    """

    app_name = forms.CharField(label='Название приложения', required=True)
    db_name = forms.CharField(label='Имя БД', required=True)

    def clean(self):
        """
        Проверка на валидацию
        :return:
        """
        cleaned_data = super().clean()
        if DataBase.objects.filter(name=cleaned_data.get('db_name')).exists():
            raise forms.ValidationError({'db_name': 'Для указанной базы уже проведены настройки репликации'})
        try:
            options = connect(cleaned_data.get('db_name'))
            pgconnect(**options)
        except Exception:
            raise forms.ValidationError({'db_name': 'Приложения или БД с таким именем не существует'})

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['app_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['db_name'].widget.attrs.update({'class': 'form-control'})

database_separator/views.py
import traceback

from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from django.core.management import call_command
from django.views.generic import ListView, TemplateView, DetailView, FormView
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy

from .models import DataBase, ReplicationSlot, CheckSum
from .forms import SeparationForm
from .scripts.separation import ActionSet, BackupActionSet
from .scripts.relaunch import ActionSetForRelaunch
from .scripts.checksums import save_check_sums


class MyLoginView(LoginView):
    """
    Вьюшка для авторизации
    """
    def get_success_url(self):
        return reverse_lazy('index')


class IndexTemplateView(TemplateView):
    """
    Вьюшка для главной страницы
    контекст:
        db_list - список БД
        slot_list - список слотов
    """
    def get_context_data(self):
        context = super().get_context_data()
        context['db_list'] = DataBase.objects.all()
        context['slot_list'] = ReplicationSlot.objects.all().order_by('active')
        return context


class DataBaseDetailView(DetailView):
    """
    Детализация сущностей в БД
    """
    model = DataBase
    template_name = 'database_separator/database_detail.html'


class SeparationView(FormView):
    """
    Вьюшка для разделения
    """
    form_class = SeparationForm
    success_url = reverse_lazy('index')
    template_name = 'database_separator/separate.html'

    def form_valid(self, form):
        if form.is_valid():
            app_name = form.cleaned_data.get('app_name')
            db_name = form.cleaned_data.get('db_name')
            action_set = ActionSet(app_name=app_name, db_name=db_name)
            try:
                action_set.execute_script()  # запускаем сценарий разделения
            except Exception:  # при возникновении ошибки
                backup_action_set = BackupActionSet(app_name=app_name, db_name=db_name)
                backup_action_set.backup()  # удаляем все сущности из БД, если есть
                tb = traceback.format_exc()  # выводим трейсбэк на страницу
                context = {'error': str(tb)}
                return render(self.request, 'database_separator/fail.html', context)
        return redirect(self.success_url)


class CheckView(TemplateView):
    """
    Вспомогательная вьюшка для проверки выполнения предварительных действий
    """
    template_name = 'database_separator/check.html'


class AdditionalFunctionalityView(TemplateView):
    """
    Вьюшка для дополнительных функций
    """
    template_name = 'database_separator/additional.html'


class CheckSumsView(ListView):
    """
    Вьюшка для отображения контрольных сумм
    """
    model = CheckSum
    paginate_by = 10

    def get_queryset(self):
        return CheckSum.objects.all().order_by('-date')


def initialize(request):
    call_command('initialize')
    return HttpResponseRedirect(reverse_lazy('index'))


def replication_relaunch(request):
    action_set = ActionSetForRelaunch()
    action_set.execute_script()
    return HttpResponseRedirect(reverse_lazy('index'))


def checksums(request):
    save_check_sums()
    return HttpResponseRedirect(reverse_lazy('database_separator:checksums'))

templates/database_separator/additional.html
{% extends 'base.html' %}
{% block content %}
<div class="main-content" id="panel">
    <div class="header bg-primary pb-6">
    </div>
    <div class="container-fluid mt--6">
        <div class="card">
            <div class="card-header">
                Выберите действие
            </div>
            <div class="card-body">
                <p>
                    <a class="btn btn-primary" href="{% url 'database_separator:initialize' %}">
                        <span class="nav-link-text">Инициализация</span>
                    </a>
                </p>
                <p>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                        Перезапуск репликации
                    </button>
                </p>

                <p>
                    <a class="btn btn-slack" href="{% url 'database_separator:save_checksums' %}">
                        <span class="nav-link-text">Создать контрольную сумму</span>
                    </a>
                </p>
                    <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
                     aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Подтверждение действия</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Вы уверены, что хотите сбросить и восстановить настройки репликации заново?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                                <a class="btn btn-danger" href="{% url 'database_separator:relaunch' %}">
                                    <span class="nav-link-text">Перезапустить</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/database_separator/check.html
{% extends 'base.html' %}
{% block content %}
<div class="main-content" id="panel">
    <div class="header bg-primary pb-6">
    </div>
    <div class="container-fluid mt--6">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Проверка выполнения предварительных действий</h5>
            </div>
            <div class="card-body">
                <div class="table-responsive" id="check-table">
                    <table class="table">
                        <tbody>
                        <tr>
                            <td>
                                <strong>
                                    Создай БД для нового приложения
                                </strong>
                            </td>
                            <td>
                                <input type="checkbox">
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <strong>
                                    Проведи миграции (начиная с office, чтобы репликация не сломалась)
                                </strong>
                            </td>
                            <td>
                                <input type="checkbox">
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <strong>
                                    Добавь БД в список баз в файле настроек BPM Liberty
                                </strong>
                            </td>
                            <td>
                                <input type="checkbox">
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <strong>
                                    Добавь роутер для нового приложения
                                </strong>
                            </td>
                            <td>
                                <input type="checkbox">
                            </td>
                        </tr>
                        </tbody>
                        <tr>
                            <td></td>
                            <td>
                                <a class="btn btn-primary active" href="{% url 'database_separator:separate' %}"
                                   id="check-button">
                                    Начать
                                </a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/database_separator/checksum_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="main-content" id="panel">
        <div class="header bg-primary pb-6">
        </div>
        <div class="container-fluid mt--6">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Контрольные суммы</h5>
                </div>
                <div class="card-body">
                    <div class="table-responsive" id="check-table">
                        <table class="table">
                            <tbody>
                            <tr>
                                <th>Дата</th>
                                <th>Сумма</th>
                            </tr>
                            {% for object in checksum_list %}
                                <tr>
                                    <td>
                                        {{ object.date|date:"H:i d.m.Y" }}
                                    </td>
                                    <td>
                                        {{ object.checksum }}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="datatable-footer">
                        <div class='dataTables_paginate paging_simple_numbers'>

                            {% if is_paginated %}
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                            >&laquo;</a
                                            >
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link" href="#">&laquo;</a>
                                        </li>
                                    {% endif %} {% for i in paginator.page_range %} {% if page_obj.number == i %}
                                    <li class="page-item"><a class="page-link active">{{ i }}</a></li>
                                {% else %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                    </li>
                                {% endif %} {% endfor %} {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.next_page_number }}" class="page-link"
                                        >&raquo;</a
                                        >
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&raquo;</a>
                                    </li>
                                {% endif %}
                                </ul>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/database_separator/database_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="main-content" id="panel">
    <div class="header bg-primary pb-6">
    </div>
    <div class="container-fluid mt--6">
        <div class="row">
            <div class="col-xl-4">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">Публикации</h3>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive table-hover">
                        <!-- Projects table -->
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col">Название</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for pub in object.publications.all %}
                            <tr class="clickable" data-toggle="collapse" id="row1" data-target=".row1">
                                <td>
                                    <strong>{{ pub.name }}</strong>
                                </td>
                                <td>
                                    <button class="btn btn-sm"><i class="ni ni-bullet-list-67"></i></button>
                                </td>
                            </tr>
                            {% for table in pub.tables.all %}
                            <tr class="collapse row1">
                                <td>
                                    {{table.name}}
                                </td>
                                <td></td>
                            </tr>
                            {% endfor %}
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-xl-4">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">Подписки</h3>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <!-- Projects table -->
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col">Название</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for sub in object.subscriptions.all %}
                            <tr>
                                <td>
                                    <strong>{{ sub.name }}</strong>
                                </td>
                                {% endfor %}
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-xl-4">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">Слоты репликации</h3>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <!-- Projects table -->
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col">Название</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for slot in object.replication_slots.all %}
                            <tr>
                                <td>
                                    <strong>{{ slot.name }}</strong>
                                </td>
                                {% endfor %}
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/database_separator/fail.html
{% extends 'base.html' %}
{% block content %}
<div class="main-content" id="panel">
    <div class="header bg-primary pb-6">
    </div>
    <div class="container-fluid mt--6">
        <div class="card">
            <div class="card-body">
                {{ error }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/database_separator/separate.html
{% extends 'base.html' %}
{% block content %}
<div class="main-content" id="panel">
    <div class="header bg-primary pb-6">
    </div>
    <div class="container-fluid mt--6">
        <form method="post">
            {% csrf_token %}
            <div class="form-group row">
                <div class="col-lg-6">

                    <!-- Basic layout-->
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">Введи необходимые данные</h5>
                        </div>

                        <div class="card-body">
                            <div class="form-group">
                                <label>{{form.app_name.label}}</label>
                                {{form.app_name}}
                                {% if form.app_name.errors %}
                                <span class='form-text text-danger'>{{ form.app_name.errors }}</span>
                                {% endif %}
                            </div>
                            <div class="form-group">
                                <label>{{form.db_name.label}}</label>
                                {{form.db_name}}
                                {% if form.db_name.errors %}
                                <span class='form-text text-danger'>{{ form.db_name.errors }}</span>
                                {% endif %}
                            </div>

                            <div class="text-right">
                                <button type="submit" class="btn btn-primary">Начать</button>
                            </div>
                        </div>
                    </div>
                    <!-- /basic layout -->
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}