database_separator/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import DataBaseDetailView, SeparationView, CheckView, AdditionalFunctionalityView, CheckSumsView, \
    initialize, replication_relaunch, checksums


app_name = 'database_separator'

urlpatterns = [
    path('database/<int:pk>', login_required(DataBaseDetailView.as_view()), name='db'),
    path('checksums', login_required(CheckSumsView.as_view()), name='checksums'),
    path('separate', login_required(SeparationView.as_view()), name='separate'),
    path('check/', login_required(CheckView.as_view()), name='check'),
    path('additional', login_required(AdditionalFunctionalityView.as_view()), name='additional'),
    path('initialize', login_required(initialize), name='initialize'),
    path('relaunch', login_required(replication_relaunch), name='relaunch'),
    path('save_checksums', login_required(checksums), name='save_checksums')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views import generic
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required

from database_separator.views import MyLoginView, IndexTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('database_separator/', include('database_separator.urls', namespace='database_separator')),
    path('accounts/login/', MyLoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('', login_required(IndexTemplateView.as_view(template_name='index.html')), name='index')
]

urlpatterns += staticfiles_urlpatterns()

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Database Separator{% endblock %}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
    <link rel="stylesheet" href="{% static 'assets/vendor/nucleo/css/nucleo.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}"
          type="text/css">
    <link rel="stylesheet" href="{% static 'assets/css/argon.css' %}?v=1.2.0'" type="text/css">

    <script src="{% static 'assets/vendor/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/js-cookie/js.cookie.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}"></script>
    <script href="{% static 'assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js' %}"></script>
    <!-- Optional JS -->
    <script src="{% static 'assets/vendor/chart.js/dist/Chart.min.js' %}"></script>
    <script src="{% static 'assets/vendor/chart.js/dist/Chart.extension.js' %}"></script>
    <!-- Argon JS -->
    <script src="{% static 'assets/js/argon.js' %}?v=1.2.0"></script>
    <script src="{% static 'assets/js/scripts.js' %}"></script>
</head>


<body>
    {% block navbartop %}
        {% include 'navbartop.html' %}
    {% endblock %}

    {% block navbar %}
        {% include 'navbar.html' %}
    {% endblock %}

    {% block content %}
    {% endblock %}
<footer class="footer pt-0">
    {% block footer %}
    {% endblock %}
</footer>

</body>
</html>

templates/index.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
<div class="main-content" id="panel">
    <!-- Header -->
    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row">
                    {% for db in db_list %}
                    <div class="col-xl-3 col-md-6">
                        <div class="card card-stats"
                             onclick="location.href='{% url 'database_separator:db' pk=db.id %}'"
                             style="cursor: pointer;">
                            <!-- Card body -->
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <span class="h2 font-weight-bold mb-0">{{db.name}}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

            </div>
        </div>
    </div>
    <div class="container-fluid mt--6">
        <div class="row">
            <div class="card col-md-12">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col">
                            <h3 class="mb-0">Активность репликации</h3>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <!-- Projects table -->
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">Название</th>
                            <th scope="col">Активен</th>
                        </tr>
                        </thead>
                        {% for slot in slot_list %}
                        <tbody>
                        <tr>
                            <td>
                                <strong>{{slot.name}}</strong>
                            </td>
                            <td>
                                {% if slot.active %}
                                <span class="fas fa-check-square" style='font-size:24px;color:green'></span>
                                {% else %}
                                <span class="fas fa-window-close" style='font-size:24px;color:red'></span>
                                {% endif %}
                            </td>
                        </tr>
                        </tbody>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/navbar.html
{% load static %}
<!-- Sidenav -->
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
        <!-- Brand -->
        <div class="sidenav-header  align-items-center">
            <a class="navbar-brand" href="{% url 'index' %}">
                <img src="{% static '/assets/img/brand/blue.png' %}" class="navbar-brand-img" alt="...">
            </a>
        </div>
        <div class="navbar-inner">
            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                <!-- Nav items -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'database_separator:checksums' %}">
                            <i class="ni ni-archive-2"></i>
                            <span class="nav-link-text">Контрольные суммы</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'database_separator:check' %}">
                            <i class="ni ni-scissors text-default"></i>
                            <span class="nav-link-text">Разделить</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'database_separator:additional' %}">
                            <i class="ni ni-fat-add"></i>
                            <span class="nav-link-text">Дополнительный функционал</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>
<!-- Main content -->


templates/navbartop.html
{% load static %}
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
</nav>

templates/navigation.html
{% load static %}
<!-- Navigation -->
<ul class="navbar-nav mb-md-3">
    <li class="nav-item">
        <a class="nav-link"
           href="https://demos.creative-tim.com/argon-dashboard/docs/getting-started/overview.html"
           target="_blank">
            <i class="ni ni-spaceship"></i>
            <span class="nav-link-text">Getting started</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/foundation/colors.html"
           target="_blank">
            <i class="ni ni-palette"></i>
            <span class="nav-link-text">Foundation</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/components/alerts.html"
           target="_blank">
            <i class="ni ni-ui-04"></i>
            <span class="nav-link-text">Components</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/plugins/charts.html"
           target="_blank">
            <i class="ni ni-chart-pie-35"></i>
            <span class="nav-link-text">Plugins</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link active active-pro" href="upgrade.html">
            <i class="ni ni-send text-dark"></i>
            <span class="nav-link-text">Upgrade to PRO</span>
        </a>
    </li>
</ul>